### ISSUE TITLE
Marking up components within InkScape

### ISSUE THREAD

**Issue by veljkopopovic** [hers-belgrade/fabric.js_components#1]
All GUI elements should have appropriate marks within SVG XML file created using tools from InkScape toolbox.
1. You should create tools within InkScape to enable designer automatic element creation
2. factory on JS side which should read layer elements and create elements upon XML marks with appripriate arguments as well

This way full control of creating GUI components is moved to design time, allowing designer to visually prepare all required elements

**Comment by andrija-hers** [comment]
Agreed completely - I'm starting to see some rudimentary traces of a gaming
engine here
